# FabCore Agent Configuration

# Central API WebSocket URL
centralApiUrl: wss://10.0.0.12:6001/agent/ws
devApiUrl: wss://localhost:8000/agent/ws

# Logging level (DEBUG, INFO, WARNING, ERROR)
logLevel: INFO

# Connection settings
maxReconnectAttempts: 500
reconnectDelaySec: 5
